server {
    listen 80;
    server_name terminal.digix.kr;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/web-terminal-acme;
        default_type text/plain;
        try_files $uri =404;
    }
    location / {
        return 301 https://terminal.digix.kr$request_uri;
    }
}
